### ISSUE TITLE
Ignore dist?

### ISSUE THREAD

**Issue by gblakeman** [jonathanawesome/blanket#5]
I typically set a `/build` or `/dist` directory to be ignored by git and not checked in to the repo. I mainly do this since I generally rely on build/CI servers for code checks and deployment and consider the build directory as something that can be removed and rebuilt at any time.

**Comment by gblakeman** [comment]
Thoughts @jonathanawesome? Would you be open to ignoring it, do you tend to build locally and commit the build as part of the project repo?

**Comment by jonathanawesome** [comment]
I use blanket as a true starter theme because most Wordpress projects need more than just the theme under version control (plugins, languages, favicon, PWA bits in root). I keep a local Wordpress install solely for the purpose of running/updating/modifying blanket and ensuring that it works with the latest version of WP. For new projects the zip gets pulled down to the theme directory, I do work using npm run dev inside the theme, and commit and branch from the wider repo.

**Comment by jonathanawesome** [comment]
That said, your changes are awesome if you're using CI and wider project coverage isn't necessary. Your fork is looking super modern...it's the Tesla of WP themes!

**Comment by gblakeman** [comment]
I figured you were committing the wider Wordpress project and deploying it.

I'm open to a parallel release branch. Let me get the setup a bit more dialed for my project and see how it fleshes out before I commit code on your end.

**Comment by gblakeman** [comment]
I can close this for now…
